# preprocessing_scripts/04_build_grid_covariates.R
# Purpose: Compute landscape covariates for each accessible 10 km grid cell:
#   1) mean_radiance, log1p_radiance  — VIIRS annual composites, multi-year average
#   2) pct_developed                  — NLCD 2019 Developed classes (proportion)
#   3) pct_protected                  — PAD-US 4.1 GAP Status 1–3 (proportion)
#   4) pop_density, log1p_pop_density — GPWv4 population density, area-weighted mean
#
# Inputs (generated by upstream scripts):
#   data/processed/grid/ca_grid10km_accessible.gpkg  (from preprocessing_scripts/03)
#
# Inputs (must be downloaded manually before running this script):
#   The four raw datasets below are not included in the repository due to size.
#   Download each to the specified path before running.
#
#   data/raw/viirs/v21/*.tif  and  data/raw/viirs/v22/*.tif
#     VIIRS Nighttime Lights annual composites (VNL v2.1 for 2012–2021, v2.2 for 2022–2024)
#     Source: Earth Observation Group, Payne Institute
#     https://eogdata.mines.edu/products/vnl/
#
#   data/raw/covariates/Annual_NLCD_LndCov_2019_CU_C1V1.tif
#     National Land Cover Database 2019
#     Source: Multi-Resolution Land Characteristics Consortium (MRLC)
#     https://www.mrlc.gov/
#
#   data/raw/covariates/PADUS4_1VectorAnalysis_PADUS_Only.gdb
#     Protected Areas Database of the United States, Version 4.1
#     Source: USGS Gap Analysis Project
#     https://www.usgs.gov/programs/gap-analysis-project/science/pad-us-data-download
#
#   data/raw/covariates/population_density_2020.tif
#     Gridded Population of the World, Version 4 (rev. 11), 2020
#     Source: NASA SEDAC / CIESIN
#     https://www.earthdata.nasa.gov/data/catalog/sedac-ciesin-sedac-gpwv4-popdens-r11-4.11
#
# Outputs:
#   data/processed/covariates_grid/grid_covariates_10km.csv

source(here::here("preprocessing_scripts", "00_setup.R"))

library(sf)
library(terra)
library(dplyr)
library(readr)
library(stringr)
library(tibble)
library(purrr)
library(exactextractr)

CA_EPSG <- 3310

# ---- Paths ----
GRID_GPKG <- file.path(DIR_GRID_PROC, "ca_grid10km_accessible.gpkg")
OUT_CSV   <- file.path(DIR_COV_GRID_PROC, "grid_covariates_10km.csv")

VIIRS_V21_DIR <- file.path(DIR_VIIRS_RAW, "v21")
VIIRS_V22_DIR <- file.path(DIR_VIIRS_RAW, "v22")

NLCD_TIF  <- file.path(DIR_COV_RAW, "Annual_NLCD_LndCov_2019_CU_C1V1.tif")
PADUS_GDB <- file.path(DIR_COV_RAW, "PADUS4_1VectorAnalysis_PADUS_Only.gdb")
POP_TIF   <- file.path(DIR_COV_RAW, "population_density_2020.tif")

# ---- Input checks ----
if (!file.exists(GRID_GPKG)) stop("Missing grid file: ", GRID_GPKG, "\nRun preprocessing_scripts/03_build_grid_and_domain.R first.")
if (!dir.exists(VIIRS_V21_DIR) && !dir.exists(VIIRS_V22_DIR)) stop("Missing VIIRS folders in: ", DIR_VIIRS_RAW)
if (!file.exists(NLCD_TIF))  stop("Missing NLCD file: ", NLCD_TIF)
if (!dir.exists(PADUS_GDB))  stop("Missing PAD-US geodatabase: ", PADUS_GDB)
if (!file.exists(POP_TIF))   stop("Missing population density raster: ", POP_TIF)

# ---- Load grid ----
grid <- st_read(GRID_GPKG, quiet = TRUE) %>%
  st_make_valid() %>%
  st_transform(CA_EPSG)

stopifnot("cell_id" %in% names(grid))

grid_v <- terra::vect(grid)

# ---- 1. VIIRS nighttime light radiance (multi-year average) ----
viirs_files <- c(
  list.files(VIIRS_V21_DIR, pattern = "\\.tif$", full.names = TRUE),
  list.files(VIIRS_V22_DIR, pattern = "\\.tif$", full.names = TRUE)
)

if (length(viirs_files) == 0) stop("No VIIRS .tif files found in v21/v22 folders.")

# Extract year from filename (expects 4-digit year in the basename)
extract_year <- function(x) {
  m <- str_match(basename(x), "(201[2-9]|202[0-4])")[, 2]
  as.integer(m)
}

viirs_index <- tibble(file = viirs_files, year = map_int(viirs_files, extract_year)) %>%
  filter(!is.na(year)) %>%
  distinct(year, .keep_all = TRUE) %>%
  arrange(year)

message("VIIRS years used: ", paste(viirs_index$year, collapse = ", "))

# Extract area-weighted mean radiance per grid cell for a single year
extract_viirs_mean_one <- function(tif_path, year_val) {
  r <- terra::rast(tif_path)
  
  # Crop/mask in native CRS (WGS 84) for speed, then reproject
  grid_4326 <- st_transform(grid, 4326)
  r_crop <- terra::crop(r, terra::vect(grid_4326)) |> terra::mask(terra::vect(grid_4326))
  r_ae <- terra::project(r_crop, paste0("EPSG:", CA_EPSG), method = "bilinear")
  
  means <- exactextractr::exact_extract(r_ae, st_transform(grid, CA_EPSG), "mean")
  
  tibble(cell_id = grid$cell_id, year = year_val, mean_radiance = means)
}

viirs_cell_year <- purrr::pmap_dfr(
  list(viirs_index$file, viirs_index$year),
  ~ extract_viirs_mean_one(..1, ..2)
)

# Average across all years for a single long-term radiance value per cell
viirs_cov <- viirs_cell_year %>%
  group_by(cell_id) %>%
  summarise(
    viirs_years = sum(!is.na(mean_radiance)),
    mean_radiance = mean(mean_radiance, na.rm = TRUE),
    log1p_radiance = log1p(mean_radiance),
    .groups = "drop"
  )

# ---- 2. Percent developed land (NLCD 2019) ----
message("Using NLCD raster: ", NLCD_TIF)

nlcd <- terra::rast(NLCD_TIF)

# Project grid to NLCD CRS for correct categorical extraction
grid_v_nlcd <- terra::vect(st_transform(grid, terra::crs(nlcd)))
nlcd_crop <- terra::crop(nlcd, grid_v_nlcd) |> terra::mask(grid_v_nlcd)

# Count pixels per land cover class within each cell
ex_tab <- terra::extract(nlcd_crop, grid_v_nlcd, fun = table, na.rm = TRUE)

ex_tbl <- tibble::as_tibble(ex_tab) %>%
  mutate(ID = as.integer(ID))

class_cols <- setdiff(names(ex_tbl), "ID")
developed_cols <- class_cols[grepl("^Developed", class_cols)]

if (length(developed_cols) == 0) {
  stop(
    "No NLCD class columns start with 'Developed'.\n",
    "Inspect names(ex_tbl) to confirm class label columns were created."
  )
}

# Compute proportion of developed pixels per cell
dev_cov <- ex_tbl %>%
  mutate(
    total_cells = rowSums(across(all_of(class_cols)), na.rm = TRUE),
    dev_cells   = rowSums(across(all_of(developed_cols)), na.rm = TRUE),
    pct_developed = if_else(total_cells > 0, dev_cells / total_cells, NA_real_)
  ) %>%
  left_join(
    tibble(
      ID = as.integer(seq_len(nrow(grid))),
      cell_id = grid$cell_id
    ),
    by = "ID"
  ) %>%
  select(cell_id, pct_developed)

# ---- 3. Percent protected land (PAD-US 4.1, GAP Status 1–3) ----
padus_layers <- sf::st_layers(PADUS_GDB)
PADUS_LAYER <- padus_layers$name[[1]]
gap_field <- "GAP_Sts"

message("Using PAD-US layer: ", PADUS_LAYER)
message("Using GAP field:    ", gap_field)

padus <- st_read(PADUS_GDB, layer = PADUS_LAYER, quiet = TRUE) %>%
  st_make_valid() %>%
  st_transform(st_crs(grid))

# Subset to polygons that intersect the grid for speed
padus <- padus[st_intersects(padus, grid, sparse = FALSE) %>% apply(1, any), ]

if (!(gap_field %in% names(padus))) {
  stop("Expected GAP field not found: ", gap_field, "\nInspect names(padus) to confirm.")
}

# Filter to GAP Status 1–3 (highest protection levels)
gap_vals <- suppressWarnings(as.integer(padus[[gap_field]]))
padus_prot <- padus[!is.na(gap_vals) & gap_vals %in% c(1, 2, 3), ]

if (nrow(padus_prot) == 0) {
  warning("No PAD-US polygons left after filtering GAP 1–3. pct_protected will be NA.")
  prot_cov <- tibble(cell_id = grid$cell_id, pct_protected = NA_real_)
} else {
  # Compute protected area fraction via spatial intersection
  inter <- st_intersection(
    grid %>% select(cell_id),
    padus_prot 
  )
  
  inter_area <- inter %>%
    mutate(a = as.numeric(st_area(.))) %>%
    st_drop_geometry() %>%
    group_by(cell_id) %>%
    summarise(protected_area_m2 = sum(a, na.rm = TRUE), .groups = "drop")
  
  cell_area <- grid %>%
    mutate(cell_area_m2 = as.numeric(st_area(.))) %>%
    st_drop_geometry() %>%
    select(cell_id, cell_area_m2)
  
  prot_cov <- cell_area %>%
    left_join(inter_area, by = "cell_id") %>%
    mutate(
      protected_area_m2 = coalesce(protected_area_m2, 0),
      pct_protected = pmin(pmax(protected_area_m2 / cell_area_m2, 0), 1)
    ) %>%
    select(cell_id, pct_protected)
}

# ---- 4. Population density (GPWv4, area-weighted mean per cell) ----
pop <- terra::rast(POP_TIF)

# Crop/mask in native CRS, then reproject to CA Albers for extraction
grid_v_pop <- terra::vect(st_transform(grid, terra::crs(pop)))
pop_crop <- terra::crop(pop, grid_v_pop) |> terra::mask(grid_v_pop)
pop_ae <- terra::project(pop_crop, paste0("EPSG:", CA_EPSG), method = "bilinear")

pop_mean <- exactextractr::exact_extract(pop_ae, st_transform(grid, CA_EPSG), "mean")

pop_cov <- tibble(
  cell_id = grid$cell_id,
  pop_density = pop_mean,
  log1p_pop_density = log1p(pop_mean)
)

# ---- Combine all covariates and write ----
covars <- tibble(cell_id = grid$cell_id) %>%
  left_join(viirs_cov, by = "cell_id") %>%
  left_join(dev_cov, by = "cell_id") %>%
  left_join(prot_cov, by = "cell_id") %>%
  left_join(pop_cov, by = "cell_id") %>%
  mutate(
    pct_developed = pmin(pmax(pct_developed, 0), 1),
    pct_protected = pmin(pmax(pct_protected, 0), 1)
  ) %>%
  arrange(cell_id)

readr::write_csv(covars, OUT_CSV)

# ---- Console summary ----
message("Saved grid covariates: ", OUT_CSV)
message("Rows (grid cells): ", nrow(covars))
message("Missingness: radiance=", sum(is.na(covars$mean_radiance)),
        " developed=", sum(is.na(covars$pct_developed)),
        " protected=", sum(is.na(covars$pct_protected)),
        " pop=", sum(is.na(covars$pop_density)))