---
title: "03_county_temporal_case_study"
output: html_notebook
---

```{r}
library(tidyverse)

# Read in the dataset
dat <- readr::read_csv(
  here::here("data", "processed", "bats_viirs_covars_county_year_species.csv"),
  show_col_types = FALSE
)
```

```{r}
#Collapse to county-year (combining species) for exploration
county_year <- dat %>%
  group_by(GEOID, county_name, year) %>%
  summarise(
    total_bats = sum(n_obs),
    mean_radiance = first(mean_radiance),
    pct_developed = first(pct_developed),
    pct_protected = first(pct_protected),
    .groups = "drop"
  )
```

```{r}
#Find counties with increasing light pollution
radiance_change <- county_year %>%
  group_by(GEOID, county_name) %>%
  summarise(
    radiance_start = mean_radiance[year == min(year)],
    radiance_end   = mean_radiance[year == max(year)],
    radiance_change = radiance_end - radiance_start,
    .groups = "drop"
  ) %>%
  arrange(desc(radiance_change))

radiance_change %>% slice_head(n = 10)

```

```{r}
#San Joaquin had the biggest radiance increase by 1.694.
case_county <- "Alameda"

#Create the case study dataset
case_data <- county_year %>%
  filter(county_name == case_county)
```



```{r}
#Light pollution trend

ggplot(case_data, aes(year, mean_radiance)) +
  geom_line(size = 1.2) +
  geom_point() +
  labs(
    title = paste("Nighttime Light Trend:", case_county, "County"),
    y = "Mean VIIRS Radiance"
  ) +
  theme_minimal()
```





```{r}
#Bat observations over time

ggplot(case_data, aes(year, total_bats)) +
  geom_line(size = 1.2) +
  geom_point() +
  labs(
    title = paste("Bat Observations Over Time:", case_county, "County"),
    y = "Total Observations"
  ) +
  theme_minimal()
```


```{r}
#Combined visualization
ggplot(case_data) +
  geom_line(aes(year, scale(mean_radiance)), color = "orange", size = 1.2) +
  geom_line(aes(year, scale(total_bats)), color = "darkblue", size = 1.2) +
  labs(
    title = paste("Urbanization vs Bat Observations:", case_county),
    y = "Scaled Value",
    caption = "Orange = Light Pollution | Blue = Bat Observations"
  ) +
  theme_minimal()
```

















